import { GoogleGenAI } from "@google/genai";

// Converts a blob to a base64 string
const blobToBase64 = (blob: Blob): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      const base64String = reader.result as string;
      // Remove data url prefix (e.g. "data:image/jpeg;base64,")
      resolve(base64String.split(',')[1]);
    };
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
};

export const cleanThumbnail = async (imageUrl: string, apiKey: string): Promise<string> => {
  if (!apiKey) throw new Error("API Key is missing. Please add your key in the Settings menu.");

  // 1. Fetch the image to get raw data
  const response = await fetch(imageUrl, { mode: 'cors' });
  if (!response.ok) throw new Error("Failed to fetch source image");
  const blob = await response.blob();
  const base64Data = await blobToBase64(blob);

  // 2. Initialize Gemini with User's Key
  const ai = new GoogleGenAI({ apiKey });
  const model = "gemini-2.5-flash-image";

  // 3. Prompt for cleaning
  const prompt = "Strictly remove all text overlays, subtitles, large titles, author names, channel icons, logos, arrows, emojis, and clickbait graphics from this YouTube thumbnail. Reconstruct the background behind these removed elements to look natural and seamless. The final image should be a clean version of the background and main subject without any superimposed UI or text.";

  try {
    const result = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
            {
                inlineData: {
                    mimeType: blob.type || 'image/jpeg',
                    data: base64Data
                }
            },
            {
                text: prompt
            }
        ]
      }
    });

    // 4. Extract the image from the response
    const parts = result.candidates?.[0]?.content?.parts;
    
    if (parts) {
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No image generated by AI");
    
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};

export const upscaleThumbnail = async (imageUrl: string, apiKey: string): Promise<string> => {
  if (!apiKey) throw new Error("API Key is missing. Please add your key in the Settings menu.");

  // 1. Fetch
  const response = await fetch(imageUrl, { mode: 'cors' });
  if (!response.ok) throw new Error("Failed to fetch source image");
  const blob = await response.blob();
  const base64Data = await blobToBase64(blob);

  // 2. Init
  const ai = new GoogleGenAI({ apiKey });
  const model = "gemini-2.5-flash-image";

  // 3. Prompt for Upscaling / Restoration
  const prompt = "Restore and enhance this photograph by improving clarity, sharpness, and image quality while preserving all original details, colors, and composition exactly as they appear - remove noise, blur, and degradation artifacts to create a professionally restored version that maintains complete authenticity without any artistic interpretation or alterations.";

  try {
    const result = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
            {
                inlineData: {
                    mimeType: blob.type || 'image/jpeg',
                    data: base64Data
                }
            },
            {
                text: prompt
            }
        ]
      }
    });

    const parts = result.candidates?.[0]?.content?.parts;
    
    if (parts) {
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No image generated by AI");
    
  } catch (error) {
    console.error("Gemini API Error (Upscale):", error);
    throw error;
  }
};

export const cleanCustomArea = async (imageWithMaskBase64: string, apiKey: string): Promise<string> => {
  if (!apiKey) throw new Error("API Key is missing. Please add your key in the Settings menu.");

  // 1. Prepare Data (Remove header if present)
  const base64Data = imageWithMaskBase64.replace(/^data:image\/(png|jpeg|jpg);base64,/, '');

  // 2. Initialize Gemini
  const ai = new GoogleGenAI({ apiKey });
  const model = "gemini-2.5-flash-image";

  // 3. Prompt for Mask-based Inpainting
  const prompt = "The bright red (#FF0000) scribbles on this image mark an area that needs to be erased. Remove the red scribbles and the object or text hidden beneath them. Fill the erased area with a natural background that seamlessly matches the surrounding texture, lighting, and colors. Do NOT change any other part of the image that is not covered by red. Return the edited image.";

  try {
    const result = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
            {
                inlineData: {
                    mimeType: 'image/png',
                    data: base64Data
                }
            },
            {
                text: prompt
            }
        ]
      }
    });

    const parts = result.candidates?.[0]?.content?.parts;
    
    if (parts) {
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No image generated by AI");
    
  } catch (error) {
    console.error("Gemini API Error (Custom Area):", error);
    throw error;
  }
};